export const ADD_TODO='ADD_TODO';
export const TOOGLE_TODO='TOOGLE_TODO';
export const SET_VISIBILITY_FILTER='SET_VISIBILITY_FILTER';
export const visibilityFilters={
    SHOW_ALL:'SHOW_ALL',
    SHOW_COMPLETED:'SHOW_COMPLETED',
    SHOW_ACTIVE:'SHOW_ACTIVE'
}